node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     dir("basics"){
     docker.withRegistry('https://index.docker.io/v1/', '75e74d1d-d8b2-40fb-929a-e529a377cfb1') {
       def app = docker.build("bigoo/docker-nodejs-demo:${commit_id}", '.').push()
     }
      sh 'pwd'
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test
      docker run --rm -tid --name docker_test -p 3000 bigoo/docker-nodejs-demo:latest
      docker kill docker_test
      
      '''
     }
   }

